import tkinter
from Constants import *
import GUI

root = tkinter.Tk()
root.title('Mastermind')

start_frame_top = tkinter.Frame(root,height=150, width = 100,bg = Colors['White'])
start_frame_top.pack(fill= 'x')
start_frame_bottom= tkinter.Frame(root,height=500, width = 400,bg = Colors['Black'])
start_frame_bottom.pack(fill= 'x')
end_frame = tkinter.Frame(root)
frame = tkinter.Frame(root)

canvas = tkinter.Canvas(frame, width=width,height=height, highlightthickness=thickness,highlightbackground='black',relief=tkinter.FLAT,bg=Colors['White'],bd=0)
end_canvas = tkinter.Canvas(end_frame, width=width,height=height, highlightthickness=thickness, highlightbackground='black', 
            relief=tkinter.FLAT, bg=Colors['White'], bd=0)
board = [['Red' for i in range(columns) ] for j in range(rows)]
pegs = [['black' for i in range(columns) ] for j in range(rows)]
Interface_object = GUI.Interface(canvas, board, pegs)
start_label = tkinter.Label(start_frame_top, text = 'Mastermind', fg = Colors['Black'])
start_label.pack(side = 'top')
start_label_2 = tkinter.Label(start_frame_top, text = '''Rules:\n\n1) You need to guess a sequence of four colours that is randomly generated by the code\n\n2) You can change the colours using the up and down arrow keys on
your keyboard.\nYou can switch between the positions in the sequence using the left and right keys.\n\n3)You will see four pegs on the right that will indicate whether your guess is correct or not and helps you to proceed further.\nA red peg indicates
that a colour as well as its position is correct.\nA white peg indicates that a colour is correct but its position is not.\nBlack peg indicates that neither the colour nor the position is correct.\n\n4) Do note that the pegs are displayed randomly and do not correspond to the position of the grid.''', bg = Colors['Black'], fg = Colors['White'])
start_label_2.pack(side = 'top') 
start_button = tkinter.Button(start_frame_bottom, text = 'Start', command = lambda:Interface_object.start_game(start_frame_bottom,start_frame_top, frame, end_canvas, end_frame))
start_button.pack(side = 'bottom')

start_frame_top.tkraise()
start_frame_bottom.tkraise()
start_frame_top.pack()
start_frame_bottom.pack()
frame.pack()
root.mainloop()




